//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_User
    {
        public string cUser_Id { get; set; }
        public string cUser_No { get; set; }
        public string cUser_Name { get; set; }
        public string cAbbrName { get; set; }
        public string cPassword { get; set; }
        public string cDept { get; set; }
        public string cDuty { get; set; }
        public string cBelongGrp { get; set; }
        public Nullable<short> nState { get; set; }
        public string cUserEmail { get; set; }
        public string cUserHand { get; set; }
        public Nullable<int> SaveMailCount { get; set; }
        public Nullable<int> SaveSMSCount { get; set; }
        public Nullable<short> iErrorCount { get; set; }
        public Nullable<System.DateTime> dPasswordDate { get; set; }
        public string cReportAuthority { get; set; }
        public string cStaff { get; set; }
        public bool bYuJing { get; set; }
        public string cpw { get; set; }
        public Nullable<System.DateTime> cpwtime { get; set; }
        public Nullable<System.DateTime> csettime { get; set; }
    }
}
