//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ERP2008Entities : DbContext
    {
        public ERP2008Entities()
            : base("name=ERP2008Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<b_Inventory> b_Inventory { get; set; }
        public DbSet<b_User> b_User { get; set; }
        public DbSet<t_opencard> t_opencard { get; set; }
        public DbSet<t_opencardpack> t_opencardpack { get; set; }
        public DbSet<t_opencardpack_sf> t_opencardpack_sf { get; set; }
        public DbSet<v_DispatchList> v_DispatchList { get; set; }
        public DbSet<SO_SODetails> SO_SODetails { get; set; }
        public DbSet<SO_SOMain> SO_SOMain { get; set; }
        public DbSet<SA_Packs> SA_Packs { get; set; }
        public DbSet<Label_template> Label_template { get; set; }
        public DbSet<t_StAndClient_compaTable> t_StAndClient_compaTable { get; set; }
        public DbSet<t_labels> t_labels { get; set; }
        public DbSet<T_Label_UID> T_Label_UID { get; set; }
    
        public virtual int Pr_SaveSerialNumber(string client, Nullable<int> addNumber, ObjectParameter serialNumber)
        {
            var clientParameter = client != null ?
                new ObjectParameter("client", client) :
                new ObjectParameter("client", typeof(string));
    
            var addNumberParameter = addNumber.HasValue ?
                new ObjectParameter("addNumber", addNumber) :
                new ObjectParameter("addNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_SaveSerialNumber", clientParameter, addNumberParameter, serialNumber);
        }
    }
}
