//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label_template
    {
        public int Label_NO { get; set; }
        public int Post_Address { get; set; }
        public string cCusCode { get; set; }
        public string Label_Path { get; set; }
        public string Label_describe { get; set; }
        public string cMemo { get; set; }
        public string Print_Cmd { get; set; }
        public Nullable<int> select_fl { get; set; }
        public string long_wide_mm { get; set; }
    }
}
