//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_Packs
    {
        public string cPCode { get; set; }
        public string cPCname { get; set; }
        public Nullable<double> fQuantity { get; set; }
        public Nullable<double> fWeight { get; set; }
        public string cZhuShen { get; set; }
        public string cJiaoXing { get; set; }
        public string cPCCode { get; set; }
        public Nullable<double> fRate { get; set; }
        public double fSPRate { get; set; }
        public decimal fSQty { get; set; }
        public short iSNumbers { get; set; }
        public string cBoxFlag { get; set; }
        public string cMemo { get; set; }
        public string cOther { get; set; }
        public short iState { get; set; }
        public Nullable<decimal> FPKminqty { get; set; }
        public string cPacking { get; set; }
        public string packagesize { get; set; }
        public string cCuscode_similar { get; set; }
        public string cInvStd_ismilar { get; set; }
        public string not_cInvStd_ismilar { get; set; }
    }
}
