//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SODetails
    {
        public int AutoID { get; set; }
        public string cSOCode { get; set; }
        public string cInvCode { get; set; }
        public Nullable<System.DateTime> dPreDate { get; set; }
        public Nullable<double> iQuantity { get; set; }
        public Nullable<double> iNum { get; set; }
        public Nullable<double> iQuotedPrice { get; set; }
        public Nullable<double> iUnitPrice { get; set; }
        public Nullable<double> iTaxUnitPrice { get; set; }
        public Nullable<decimal> iMoney { get; set; }
        public Nullable<decimal> iTax { get; set; }
        public Nullable<decimal> iSum { get; set; }
        public Nullable<decimal> iDisCount { get; set; }
        public Nullable<double> iNatUnitPrice { get; set; }
        public Nullable<decimal> iNatMoney { get; set; }
        public Nullable<decimal> iNatTax { get; set; }
        public Nullable<decimal> iNatSum { get; set; }
        public Nullable<decimal> iNatDisCount { get; set; }
        public Nullable<double> iFHNum { get; set; }
        public Nullable<double> iFHQuantity { get; set; }
        public Nullable<decimal> iFHMoney { get; set; }
        public Nullable<double> iKPQuantity { get; set; }
        public Nullable<double> iKPNum { get; set; }
        public Nullable<decimal> iKPMoney { get; set; }
        public Nullable<double> iCancQty { get; set; }
        public string cMemo { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public Nullable<int> bFH { get; set; }
        public Nullable<double> KL { get; set; }
        public Nullable<double> KL2 { get; set; }
        public double iPreDisCount { get; set; }
        public string cInvName { get; set; }
        public Nullable<double> iTaxRate { get; set; }
        public string cDefine22 { get; set; }
        public string cDefine23 { get; set; }
        public string cDefine24 { get; set; }
        public string cDefine25 { get; set; }
        public Nullable<double> cDefine26 { get; set; }
        public Nullable<double> cDefine27 { get; set; }
        public string cItemCode { get; set; }
        public string cItem_class { get; set; }
        public string cItemName { get; set; }
        public string cItem_CName { get; set; }
        public string cFree3 { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public Nullable<decimal> iInvExchRate { get; set; }
        public string cUnitID { get; set; }
        public Nullable<int> iSOsID { get; set; }
        public string cDefine28 { get; set; }
        public string cDefine29 { get; set; }
        public string cDefine30 { get; set; }
        public string cDefine31 { get; set; }
        public string cDefine32 { get; set; }
        public string cDefine33 { get; set; }
        public string cFreeMemo { get; set; }
        public string cWaferKind { get; set; }
        public string cCharacter { get; set; }
        public Nullable<int> cDefine34 { get; set; }
        public Nullable<int> cDefine35 { get; set; }
        public Nullable<System.DateTime> cDefine36 { get; set; }
        public Nullable<System.DateTime> cDefine37 { get; set; }
        public Nullable<decimal> FPurQuan { get; set; }
        public Nullable<double> fSaleCost { get; set; }
        public Nullable<double> fSalePrice { get; set; }
        public string cQuoCode { get; set; }
        public Nullable<int> iQuoID { get; set; }
        public string cSCloser { get; set; }
        public Nullable<System.DateTime> dPreMoDate { get; set; }
        public Nullable<int> iRowNo { get; set; }
        public Nullable<int> iCusBomID { get; set; }
        public Nullable<decimal> iMoQuantity { get; set; }
        public string cContractID { get; set; }
        public string cContractTagCode { get; set; }
        public Nullable<System.Guid> cContractRowGuid { get; set; }
        public Nullable<int> iPPartSeqID { get; set; }
        public Nullable<int> iPPartID { get; set; }
        public Nullable<decimal> iPPartQty { get; set; }
        public string cCusInvCode { get; set; }
        public string cCusInvName { get; set; }
        public Nullable<double> iPreKeepQuantity { get; set; }
        public Nullable<double> iPreKeepNum { get; set; }
        public Nullable<double> iPreKeepTotQuantity { get; set; }
        public Nullable<double> iPreKeepTotNum { get; set; }
        public Nullable<decimal> O_L_ID { get; set; }
        public Nullable<decimal> NewAutoid { get; set; }
        public Nullable<double> iPlanedQty { get; set; }
        public Nullable<double> iPlanedNum { get; set; }
        public string cPreKeepUser { get; set; }
        public Nullable<bool> bPreKeepEnd { get; set; }
        public Nullable<double> iFreeKeepQuantity { get; set; }
        public Nullable<double> iFreeKeepNum { get; set; }
        public Nullable<double> iSoKeepQuantity { get; set; }
        public Nullable<double> iSoKeepNum { get; set; }
        public Nullable<double> iBackQuantity { get; set; }
        public Nullable<double> iBackNum { get; set; }
        public Nullable<double> iBackInQuantity { get; set; }
        public Nullable<double> iBackInNum { get; set; }
        public Nullable<double> iFIQuantity { get; set; }
        public Nullable<double> iFINum { get; set; }
        public Nullable<double> iSendQuantity { get; set; }
        public Nullable<double> iSendNum { get; set; }
        public Nullable<bool> bDealEndSo { get; set; }
        public Nullable<bool> bDetailsEnd { get; set; }
        public Nullable<System.DateTime> sAppraisalDate { get; set; }
        public string cOrderRemark { get; set; }
        public string Closer { get; set; }
        public Nullable<System.DateTime> dCloseTime { get; set; }
        public Nullable<double> iTransferQty { get; set; }
        public Nullable<double> iTransferNum { get; set; }
        public Nullable<decimal> iReturnQty { get; set; }
        public Nullable<decimal> iReturnNum { get; set; }
        public string cSICode2 { get; set; }
        public string pricetype { get; set; }
        public string preferentials { get; set; }
        public Nullable<decimal> prefprice { get; set; }
        public string cBillFlowType { get; set; }
        public Nullable<int> cBeginBillID { get; set; }
        public string cRunFlag { get; set; }
        public decimal iDelQty_DN { get; set; }
        public string Pack_code { get; set; }
        public string tech_remark { get; set; }
        public Nullable<bool> tech_checked { get; set; }
        public string tech_checkman { get; set; }
        public Nullable<System.DateTime> tech_checkdate { get; set; }
        public string clinvcode { get; set; }
    
        public virtual SO_SOMain SO_SOMain { get; set; }
    }
}
