//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SOMain
    {
        public SO_SOMain()
        {
            this.SO_SODetails = new HashSet<SO_SODetails>();
        }
    
        public string cSTCode { get; set; }
        public System.DateTime dDate { get; set; }
        public string cSOCode { get; set; }
        public Nullable<byte> bBusFlow { get; set; }
        public string cCusCode { get; set; }
        public string cDepCode { get; set; }
        public string cPersonCode { get; set; }
        public string cSCCode { get; set; }
        public string cCusOAddress { get; set; }
        public string cPayCode { get; set; }
        public string cexch_name { get; set; }
        public Nullable<double> iExchRate { get; set; }
        public Nullable<double> iTaxRate { get; set; }
        public Nullable<decimal> iMoney { get; set; }
        public string cMemo { get; set; }
        public Nullable<byte> iStatus { get; set; }
        public string cMaker { get; set; }
        public string cVerifier { get; set; }
        public Nullable<bool> bEndAuditing { get; set; }
        public Nullable<System.DateTime> cVerDate { get; set; }
        public string cCloser { get; set; }
        public bool bDisFlag { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public bool bReturnFlag { get; set; }
        public string cCusName { get; set; }
        public Nullable<bool> bOrder { get; set; }
        public Nullable<int> iVTid { get; set; }
        public byte[] ufts { get; set; }
        public string cChanger { get; set; }
        public string cBusType { get; set; }
        public string cCreChpName { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public string coppcode { get; set; }
        public string cLocker { get; set; }
        public Nullable<System.DateTime> dPreMoDateBT { get; set; }
        public Nullable<System.DateTime> dPreDateBT { get; set; }
        public string cAddCode { get; set; }
        public bool bEnd { get; set; }
        public bool bPrint { get; set; }
        public short iExchange { get; set; }
        public string cSICode { get; set; }
        public Nullable<System.DateTime> dTransWTDate { get; set; }
        public short iWTNums { get; set; }
        public Nullable<int> iEndUseType { get; set; }
        public string cEndUseName { get; set; }
        public string cEndUseCode { get; set; }
        public string cBeginBillCode { get; set; }
    
        public virtual ICollection<SO_SODetails> SO_SODetails { get; set; }
    }
}
