//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_labels
    {
        public int AutoId { get; set; }
        public string code { get; set; }
        public string createDate { get; set; }
        public string shipmentDate { get; set; }
        public int labelTemplateAddressId { get; set; }
        public string clientCode { get; set; }
        public string typeCode { get; set; }
        public string orderCode { get; set; }
        public string pn { get; set; }
        public string po { get; set; }
        public string type { get; set; }
        public string package { get; set; }
        public string flowCard { get; set; }
        public string workOrder { get; set; }
        public string batchNo { get; set; }
        public int qty { get; set; }
        public long serialNumber { get; set; }
        public string vendorCode { get; set; }
        public string ClientRequireOne { get; set; }
        public string ClientRequireTwo { get; set; }
        public string ClientRequireThree { get; set; }
        public string ClientRequireFour { get; set; }
        public string ClientRequireFive { get; set; }
        public string UID { get; set; }
        public int packType { get; set; }
        public string remark { get; set; }
    }
}
