//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Label_UID
    {
        public int auto_id { get; set; }
        public string Client_code { get; set; }
        public long SerialNumber { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public System.DateTime ResetDate { get; set; }
        public Nullable<int> ResetDay { get; set; }
        public string Describe { get; set; }
    }
}
