//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_opencard
    {
        public string Fopenkno { get; set; }
        public string Ftype { get; set; }
        public string FOperator { get; set; }
        public Nullable<System.DateTime> FRptDate { get; set; }
        public string Fopenktype { get; set; }
        public string FRouteNo { get; set; }
        public string FWcNo { get; set; }
        public int Fwoseqid { get; set; }
        public Nullable<decimal> Fopenkqty { get; set; }
        public string Fitemno { get; set; }
        public string FBatchNo { get; set; }
        public string Ffree1 { get; set; }
        public string FwfnoO { get; set; }
        public string FwfnoN { get; set; }
        public string Fsn { get; set; }
        public string FIsWorkItemO { get; set; }
        public string FIsWorkItemN { get; set; }
        public string Fman { get; set; }
        public string Fmacno { get; set; }
        public string Fwono { get; set; }
        public Nullable<System.DateTime> Fteamdate { get; set; }
        public string Fteam { get; set; }
        public string Fteams { get; set; }
        public string Fisrpt { get; set; }
        public string Fnote { get; set; }
        public string FSitem { get; set; }
        public string FDitem { get; set; }
        public string FProductNo1 { get; set; }
        public string FProductNo2 { get; set; }
        public string Fbwcno { get; set; }
        public Nullable<int> Fbwoseqid { get; set; }
        public Nullable<decimal> Fbqty { get; set; }
        public Nullable<int> Fnowwoseqid { get; set; }
        public string Fbacktype { get; set; }
        public string Fnewteam { get; set; }
        public Nullable<System.DateTime> Fnewteamdate { get; set; }
        public Nullable<decimal> Fallinqty { get; set; }
        public string pack_code { get; set; }
    }
}
