//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_opencardpack_sf
    {
        public string fbarcode { get; set; }
        public string fsn { get; set; }
        public string fwono { get; set; }
        public int fautoid { get; set; }
        public string fsn_melf { get; set; }
        public string fbatchno { get; set; }
        public string fbatchno_yaozhao { get; set; }
        public string fbatchno_melf { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public string fbatchnos { get; set; }
        public string FBatchNoall { get; set; }
        public string fsqtypcs { get; set; }
        public string cpo { get; set; }
        public string cpn { get; set; }
        public string Fpinpai { get; set; }
        public string DL { get; set; }
        public string cinvname { get; set; }
        public string toworthree { get; set; }
        public string yyyymmdd { get; set; }
        public string yyyymmdd2 { get; set; }
        public string yymmdd { get; set; }
        public string mzcinvstd { get; set; }
        public string fnote { get; set; }
        public string S4003_lz { get; set; }
        public string mzcinvstd_melf { get; set; }
        public string fzhushen { get; set; }
        public string fzhushen_youzhao { get; set; }
        public string fbatchfree { get; set; }
        public string fgetdate { get; set; }
        public string fgetdate1 { get; set; }
        public string ccuscode { get; set; }
        public string csocode { get; set; }
        public string cinvstd { get; set; }
        public Nullable<decimal> fqty { get; set; }
        public string ccharacter { get; set; }
        public string tpv { get; set; }
        public string T5223_tpv { get; set; }
        public string tpv2 { get; set; }
        public string tpv3 { get; set; }
        public string cinvdefine11 { get; set; }
        public string ffoot { get; set; }
        public string cinvdefine9 { get; set; }
        public string csocode_5 { get; set; }
        public string T5223SN { get; set; }
        public string HX_batch { get; set; }
        public string B3001_SN { get; set; }
        public string B3001_SN2 { get; set; }
        public string C4008_SN { get; set; }
        public string fgetdate2 { get; set; }
        public string cinvdefine2 { get; set; }
        public string yyyymmdd_s4023 { get; set; }
        public string etoworthree { get; set; }
        public string yyyymmdd_S4032 { get; set; }
        public Nullable<decimal> fqtykpcs { get; set; }
        public string cinvstd_p4010 { get; set; }
        public string FGETDATE6 { get; set; }
        public string TDS5007_Dc { get; set; }
        public string TDS5007_fsn { get; set; }
        public string T5223_sn { get; set; }
        public string T5223_sn2 { get; set; }
        public string wwgetdate { get; set; }
        public string TPV_Address { get; set; }
        public string csocode_mmddseq { get; set; }
        public string centerprise { get; set; }
        public string fsnitem { get; set; }
        public string CNC { get; set; }
        public string cpn2 { get; set; }
        public string cpo2 { get; set; }
        public string b3001_vendor_code { get; set; }
        public string w3001_j4012_cmemo { get; set; }
        public Nullable<decimal> WaiXiang_qty { get; set; }
        public string YY_Week { get; set; }
        public string H3005_YY_Week { get; set; }
        public string yyyymmdd_F0026 { get; set; }
        public string T5223_T { get; set; }
        public string fsqtypcs_F { get; set; }
        public string zdrq_week { get; set; }
        public string r_zhushen { get; set; }
        public string year_4 { get; set; }
        public string week_2 { get; set; }
        public string fsn_IQC { get; set; }
        public string fzhushen_tds4001 { get; set; }
        public string cFree3 { get; set; }
        public string year_month { get; set; }
        public int TDW4001_TDG4001_SAFETY { get; set; }
        public string TDW4001_TDG4001_CMEMO { get; set; }
        public string YYWWD { get; set; }
        public string cinvstd_tdg4001 { get; set; }
        public string cfree10 { get; set; }
        public string s3025 { get; set; }
        public string WD3001cmemo { get; set; }
        public Nullable<System.DateTime> dPreDate { get; set; }
        public string zd_Date { get; set; }
        public string zd_Date_YYMMDD { get; set; }
        public string fqtykpcs_dh { get; set; }
        public string fqtykpcs_F { get; set; }
        public string S4003_LT { get; set; }
        public string fqtykpcs_5 { get; set; }
        public string tpv6_qty { get; set; }
        public string cinvstd_tpv { get; set; }
        public Nullable<decimal> minPackNum { get; set; }
        public string minpackNum_Comma { get; set; }
        public string client_typename { get; set; }
        public string tradename { get; set; }
        public string J0004Item { get; set; }
        public string J0004Item2 { get; set; }
        public string yymm { get; set; }
        public Nullable<int> small_qty { get; set; }
        public Nullable<int> box_qty { get; set; }
        public Nullable<int> chest_qty { get; set; }
        public Nullable<double> soDetailSum { get; set; }
        public string labelqty_5_wei { get; set; }
        public string labelqty_dh { get; set; }
        public string T5223_Date { get; set; }
        public string zd_Date_YMMDD { get; set; }
        public string T5223_VD { get; set; }
    }
}
