//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_opencardpack
    {
        public int Fautoid { get; set; }
        public string Fopenkno { get; set; }
        public string Fbarcode { get; set; }
        public string FwfnoN { get; set; }
        public string FDitem { get; set; }
        public string FWcNo { get; set; }
        public string Fsn { get; set; }
        public string Fwono { get; set; }
        public string FBatchNo { get; set; }
        public string FBatchNos { get; set; }
        public string FBatchNoall { get; set; }
        public string FProductNo { get; set; }
        public Nullable<decimal> Fqty { get; set; }
        public Nullable<decimal> Fplanqty { get; set; }
        public string cPCode { get; set; }
        public Nullable<decimal> fsqty { get; set; }
        public Nullable<decimal> fssumqty { get; set; }
        public Nullable<decimal> FPKminqty { get; set; }
        public Nullable<decimal> FPKsumqty { get; set; }
        public Nullable<int> FsaID { get; set; }
        public string cCusCode { get; set; }
        public string cSOCode { get; set; }
        public Nullable<decimal> iNum { get; set; }
        public string cPO { get; set; }
        public string cPN { get; set; }
        public Nullable<System.DateTime> dPreDate { get; set; }
        public string cFree1 { get; set; }
        public string Fpinpai { get; set; }
        public string cinvstd { get; set; }
        public string cinvname { get; set; }
        public string mzcinvstd { get; set; }
        public string Fbqdate { get; set; }
        public string Fnote { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public string Fzhushen { get; set; }
        public string CNC { get; set; }
        public string Fbatchfree { get; set; }
        public Nullable<decimal> fsqtypcs { get; set; }
        public Nullable<decimal> fssumqtypcs { get; set; }
        public Nullable<decimal> FPKminqtypcs { get; set; }
        public Nullable<decimal> FPKsumqtypcs { get; set; }
        public string fgetdate { get; set; }
        public string fgetdate1 { get; set; }
        public string cfree10 { get; set; }
        public string cCharacter { get; set; }
        public Nullable<decimal> fqtykpcs { get; set; }
        public string wwgetdate { get; set; }
        public string fgetdate2 { get; set; }
        public string fgetdate6 { get; set; }
        public string fsnn { get; set; }
        public string zoom { get; set; }
        public string fsnn1 { get; set; }
        public string fsnfree { get; set; }
        public string ffoot { get; set; }
        public string tpv { get; set; }
        public string FBatchNoall2 { get; set; }
        public string S0066_fsn { get; set; }
        public System.DateTime gettoday { get; set; }
        public string fbatchno9 { get; set; }
        public string pack_code { get; set; }
        public Nullable<decimal> Flabelqty { get; set; }
        public string PC_suffix { get; set; }
        public string DC_suffix { get; set; }
        public string dt_suffix { get; set; }
    }
}
