//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_StAndClient_compaTable
    {
        public int autoid { get; set; }
        public string St_Type { get; set; }
        public string Client_cCusCode { get; set; }
        public string Client_PN { get; set; }
        public string Client_TypeName { get; set; }
        public string TradeName { get; set; }
        public string Free1 { get; set; }
        public string Free2 { get; set; }
        public string Free3 { get; set; }
        public string Free4 { get; set; }
        public string Free5 { get; set; }
    }
}
