//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DispatchList
    {
        public string cDLCode { get; set; }
        public string cVouchType { get; set; }
        public string cSTCode { get; set; }
        public string cSTName { get; set; }
        public string cBusType { get; set; }
        public System.DateTime dDispatchDate { get; set; }
        public string cexch_name { get; set; }
        public double iExchRate { get; set; }
        public string cCusCode { get; set; }
        public string cCusName { get; set; }
        public string cDepCode { get; set; }
        public string cPersonCode { get; set; }
        public string cMaker { get; set; }
        public string cVerifier { get; set; }
        public string cBillType { get; set; }
        public int AutoID { get; set; }
        public bool bGsp { get; set; }
        public Nullable<bool> bInspect { get; set; }
        public string cWhCode { get; set; }
        public string cInvCode { get; set; }
        public string cInvName { get; set; }
        public string cInvStd { get; set; }
        public string zhushen { get; set; }
        public string fushu { get; set; }
        public string biecheng { get; set; }
        public string baozhuang { get; set; }
        public Nullable<decimal> iQuantity { get; set; }
        public Nullable<double> fRefuseQuantity { get; set; }
        public Nullable<double> iQuotedPrice { get; set; }
        public Nullable<double> iUnitPrice { get; set; }
        public Nullable<double> iTaxUnitPrice { get; set; }
        public Nullable<decimal> iMoney { get; set; }
        public Nullable<decimal> iTax { get; set; }
        public Nullable<decimal> iSum { get; set; }
        public Nullable<double> iTaxRate { get; set; }
        public Nullable<double> KL { get; set; }
        public Nullable<double> KL2 { get; set; }
        public Nullable<decimal> iDisCount { get; set; }
        public Nullable<decimal> iNatDisCount { get; set; }
        public string csocode { get; set; }
        public string cBatch { get; set; }
        public string cMemo { get; set; }
        public string cUnitID { get; set; }
        public string cComUnitCode { get; set; }
        public bool bEndAuditing { get; set; }
        public Nullable<System.DateTime> dVerifyDate { get; set; }
        public string cInCaseType { get; set; }
        public string sInCaseDate { get; set; }
        public Nullable<short> iCaseBatch { get; set; }
        public Nullable<int> isosid { get; set; }
        public string cSoCode2 { get; set; }
        public string cFree10 { get; set; }
        public bool bPrintFlag { get; set; }
        public System.DateTime dDate { get; set; }
        public string cinvkcode { get; set; }
        public string CUSPO { get; set; }
        public string POCFREE1 { get; set; }
        public string cCusInvCode { get; set; }
        public string cFree9 { get; set; }
        public bool bInvAuditing { get; set; }
        public string csoMemo { get; set; }
        public string cFree6 { get; set; }
        public string cEPC { get; set; }
        public string coppcode { get; set; }
    }
}
